language: python

python:
    - 3.8
    - 3.7
    - 3.6

branches:
    only:
        - main

install:
    - pip install coverage
    - pip install coveralls
    - pip install flake8
    - pip install -r requirements.txt
    - pip install pytest-order
    - pip install pytest==4.5.0
    - pip install codecov==2.0.15
    - pip install pytest-cov==2.7.1

script:
    - pytest --cov=modules --cov-config=.coveragerc

after_success:
    - bash <(curl -s https://codecov.io/bash)
    - coverage report
    - coveralls