language: python

python:
    - 3.7
    - 3.6

branches:
    only:
        - main

install:
    - pip install coverage
    - pip install coveralls
    - pip install flake8
    - pip install -r requirements.txt
    - pip install pytest==4.5.0
    - pip install codecov==2.0.15
    - pip install pytest-cov==2.7.1

script:
    - pytest --cov=modules tests/test_user.py

after_success:
    - coverage report
    - coveralls

deploy:
  provider: heroku
  api_key:
    secure: "b4032cf9-e3fa-4dbc-8abb-b7ce0e13b308"
  on: main